spring:
  application:
    name: cryptoradar
  datasource:
    url: jdbc:postgresql://localhost:5432/cryptoradar
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

ethereum:
  node-url: https://sepolia.drpc.org
